lang: en-GB
title: Bethan Morgan-Williams
email:
description: Composer
baseurl: ""
url: "https://www.bethanmorganwilliams.com"

author:
  name: Bethan Morgan-Williams
  picture:

twitter_username: morganwilliamsb
instagram_username: morganwilliamsb
soundcloud_username: bethanmorganwilliams
youtube_username: morganwilliamsb

github_username:
logo: "/assets/images/logo_bmw.png"

search: true
search_full_content: true
search_provider:

algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by:

markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/

exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs
  - /example

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

collections:
  listen:
    output: true
    permalink: /:collection/:path/
